"""changes in model quote

Revision ID: 11f5e875b0bf
Revises: fe4145243970
Create Date: 2025-03-17 15:23:39.262524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11f5e875b0bf'
down_revision = 'fe4145243970'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cotizaciones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pdf_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cotizaciones', schema=None) as batch_op:
        batch_op.drop_column('pdf_url')

    # ### end Alembic commands ###
