"""empty message

Revision ID: 3c06e656a0b0
Revises: 3f79812e51e7
Create Date: 2025-03-24 21:16:30.070595

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3c06e656a0b0'
down_revision = '3f79812e51e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mensajes', schema=None) as batch_op:
        batch_op.alter_column('fecha',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.Date(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mensajes', schema=None) as batch_op:
        batch_op.alter_column('fecha',
               existing_type=sa.Date(),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###
