"""Add date in model contact us

Revision ID: 9c7e6908237d
Revises: 8b04fc3ad81e
Create Date: 2025-04-09 17:42:03.522463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c7e6908237d'
down_revision = '8b04fc3ad81e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contactanos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contactanos', schema=None) as batch_op:
        batch_op.drop_column('fecha')

    # ### end Alembic commands ###
