"""agregadas nuevas columnas a la tabla

Revision ID: fe4145243970
Revises: 
Create Date: 2025-03-17 08:12:28.176152

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fe4145243970'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('playera')
    with op.batch_alter_table('cotizaciones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('precio', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('subtotal', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total', sa.Float(), nullable=True))

    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.alter_column('precio',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('total',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.Float(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.alter_column('total',
               existing_type=sa.Float(),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=True)
        batch_op.alter_column('precio',
               existing_type=sa.Float(),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=True)

    with op.batch_alter_table('cotizaciones', schema=None) as batch_op:
        batch_op.drop_column('total')
        batch_op.drop_column('subtotal')
        batch_op.drop_column('precio')

    op.create_table('playera',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('titulo', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('descripcion', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('precio', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('imagen', mysql.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
